# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

    # Drupal specific vars.
    - DRUPAL_TI_MODULE_NAME="restful"
    - DRUPAL_TI_SIMPLETEST_GROUP="RESTful"
    - DRUPAL_TI_DB="drupal_travis_db"
    - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
    # Note: Do not add a trailing slash here.
    - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
    - DRUPAL_TI_WEBSERVER_PORT="8080"
    - DRUPAL_TI_DRUPAL_ROOT=$TRAVIS_BUILD_DIR/../../drupal-7/drupal

    # Simpletest specific commandline arguments.
    - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT $DRUPAL_TI_SIMPLETEST_GROUP"

    # PHPUnit specific commandline arguments.
    - DRUPAL_TI_PHPUNIT_ARGS=""

    # Code coverage via coveralls.io
    # - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
    # This needs to match your .coveralls.yml file.
    # - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"

    # Debug options
    #- DRUPAL_TI_DEBUG="-x -v"

  matrix:
    # - DRUPAL_TI_RUNNERS="phpunit"
    - DRUPAL_TI_RUNNERS="simpletest"

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - composer global require "lionsad/drupal_ti:dev-master"
  - drupal-ti before_install

install:
  - drupal-ti install

before_script:
  - drush dl --yes --root=$DRUPAL_TI_DRUPAL_ROOT entity
  # Patch Entity API.
  - curl -O https://www.drupal.org/files/issues/2086225-entity-access-check-node-create-3.patch
  - patch -p1 $DRUPAL_TI_DRUPAL_ROOT/sites/all/modules/entity/modules/callbacks.inc  < 2086225-entity-access-check-node-create-3.patch
  - drush dl --yes --root=$DRUPAL_TI_DRUPAL_ROOT entityreference
  - drush dl --yes --root=$DRUPAL_TI_DRUPAL_ROOT registry_rebuild
  - drush dl --yes --dev --root=$DRUPAL_TI_DRUPAL_ROOT entity_valitator
  - drush en --yes --root=$DRUPAL_TI_DRUPAL_ROOT entityreference
  - drush en --yes --root=$DRUPAL_TI_DRUPAL_ROOT entity

  - drupal-ti before_script
  - drush pm-enable --yes --root=$DRUPAL_TI_DRUPAL_ROOT restful_token_auth
  - drush rr --yes --root=$DRUPAL_TI_DRUPAL_ROOT

script:
  - drupal-ti script

after_script:
  - drupal-ti after_script
