language: php

php:
  - 5.4

env:
  - PATH=$PATH:/home/travis/.composer/vendor/bin

# This will create the database
mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Grab Drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash
  # Make sure we don't fail when checking out projects
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # LAMP package installation (mysql is already started)
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm, travis does not support any other method with php and apache
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Make sure the apache root is in our wanted directory
  - echo "$(curl -fsSL https://gist.githubusercontent.com/nickveenhof/11386315/raw/b8abaf9304fe12b5cc7752d39c29c1edae8ac2e6/gistfile1.txt)" | sed -e "s,PATH,$TRAVIS_BUILD_DIR/../drupal,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  # Set sendmail so drush doesn't throw an error during site install.
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Forward the errors to the syslog so we can print them
  - echo "error_log=syslog" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  # Get latest drupal 8 core
  - cd $TRAVIS_BUILD_DIR/..
  - git clone --depth 1 --branch 7.x http://git.drupal.org/project/drupal.git
  # Restart apache and test it
  - sudo service apache2 restart
  - curl -v "http://localhost"
  # Re-enable when trying to get CodeSniffer doesn't return a 403 anymore.
  #- composer global require drupal/coder:\>7

before_script:
  - cd $TRAVIS_BUILD_DIR/../drupal
  # Update drupal core
  - git pull origin 7.x
  # Install the site
  - drush -v site-install minimal --db-url=mysql://root:@localhost/drupal --yes
  # Increase max_allowed_packet to avoid MySQL errors
  - echo -e "[server]\nmax_allowed_packet=64M" | sudo tee -a /etc/mysql/conf.d/drupal.cnf
  - sudo service mysql restart
  - phpenv rehash

script:
  # Go to our Drupal module directory
  - mkdir $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/restful
  - cp -R $TRAVIS_BUILD_DIR/* $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/restful/
  # Go to our Drupal main directory
  - cd $TRAVIS_BUILD_DIR/../drupal

  # Download the composer pieces.
  - drush --yes dl composer-8.x-1.x
  - drush --yes dl composer_manager
  - cd $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/composer_manager
  - curl -O https://www.drupal.org/files/issues/composer_manager_autoloader.patch
  - patch -p1 < composer_manager_autoloader.patch
  - cd $TRAVIS_BUILD_DIR/../drupal
  - chmod a+w $TRAVIS_BUILD_DIR/../drupal/sites/default/settings.php
  - echo -e "\n\$conf['composer_manager_autoloader_bootstrap'] = 0;" >> $TRAVIS_BUILD_DIR/../drupal/sites/default/settings.php
  - chmod a-w $TRAVIS_BUILD_DIR/../drupal/sites/default/settings.php
  - drush --yes pm-enable composer_manager
  # Set variable to 0 to avoid automatic composer build
  - drush --yes vset --exact composer_manager_autobuild_packages 0

  # Download and enable module and its dependencies
  - drush --yes dl xautoload
  - drush --yes dl entity_validator --dev
  - drush --yes dl plug
  - drush --yes dl ctools
  - drush --yes dl entity
  - drush --yes dl entityreference

  # Enable plug and run composer.
  - drush --yes pm-enable plug
  - drush --yes composer-manager update --no-interaction --prefer-source

  # Patch Entity API.
  - curl -O https://www.drupal.org/files/issues/2086225-entity-access-check-node-create-3.patch
  - patch -p1 $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/entity/modules/callbacks.inc  < 2086225-entity-access-check-node-create-3.patch

  - curl -O https://www.drupal.org/files/issues/2264079-entity-wrapper-access-single-entity-reference-2.patch
  - patch -p1 $TRAVIS_BUILD_DIR/../drupal/sites/all/modules/entity/includes/entity.wrapper.inc < 2264079-entity-wrapper-access-single-entity-reference-2.patch

  # Enable the RESTful modules
  - drush en --yes simpletest
  - drush --yes pm-enable restful restful_token_auth restful_test
  # Run the tests
  - php $TRAVIS_BUILD_DIR/../drupal/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://localhost "RESTful" | tee /tmp/test.txt
  - TEST_EXIT=${PIPESTATUS[0]}
  - echo $TEST_EXIT
  # Check if we had fails in the run-tests.sh script
  # Exit with the inverted value, because if there are no fails found, it will exit with 1 and for us that\
  # is a good thing so invert it to 0. Travis has some issues with the exclamation mark in front so we have to fiddle a
  # bit.
  # Also make the grep case insensitive and fail on run-tests.sh regular fails as well on fatal errors.
  - TEST_OUTPUT=$(! egrep -i "([0-9]+ fails)|(PHP Fatal error)|([0-9]+ exceptions)" /tmp/test.txt > /dev/null)$?
  - echo $TEST_OUTPUT
  # if the TEST_EXIT status is 0 AND the TEST_OUTPUT status is also 0 it means we succeeded, in all other cases we
  # failed.
  - php -i | grep 'php.ini'
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/syslog | grep 'php'
  # Exit the build
  - if [ $TEST_EXIT -eq 0 ] && [ $TEST_OUTPUT -eq 0 ]; then exit 0; else exit 1; fi
